class Config :
    JWT_SECRET_KEY = 'yhacademy1029##heelo'
    JWT_ACCESS_TOKEN_EXPIRES = False
    PROPAGATE_EXCEPTIONS = True

    ACCESS_KEY = 'AKIAVO5I77VULVBKKGHT'
    SECRET_ACCESS = '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'
